### ISSUE TITLE
Requesting an Invite

### ISSUE THREAD

**Issue by davidmartinez** [uncodedlb/code-of-conduct#1]
Just a heads up, Github is new to me, but I understand the basics of version control / why it's important. I want to learn how to collaborate with it more than add merge / add code to projects for now (says the design guy). Thanks!

**Comment by mdrmike** [comment]
done, thanks for your interest!  Please [join us on our slack channel](http://j.mp/uncoded-slack) if you haven't already

Also, be sure to review our [Policy Documents](https://github.com/uncodedlb/uncoded-policies) -- we also really encourage suggestions and improvements (preferably as issue or [pull request](https://help.github.com/articles/using-pull-requests/)).
